var PROJECTS = [
  {
    id:'ey', name:'EY Fabric', accent:'#c9a227',
    src:'projects/ey-pi-player.html',
    tryUrl:'try.html?p=projects/ey-pi-player.html&beat=6',
    lede:'Research signals to a catalog people can actually publish into. Reconstructed product windows — not confidential EY screens.',
    beats:[
      {n:'01',name:'Measure',   chips:['Mixpanel','GA4','Hotjar'],   desc:'Analytics snapshot across EY Fabric catalog listings — traffic, engagement, conversion at a glance.',
       contains:['Dashboard con KPIs de tráfico, engagement y conversión','Gráfico de serie de tiempo','Tabla de top páginas','Filtro de rango de fechas']},
      {n:'02',name:'Analyze',   chips:['Mixpanel','Optimizely'],      desc:'Funnel analysis revealing where users drop across search, detail, and apply flows.',
       contains:['Visualización de funnel','Porcentajes de drop-off por paso','Etapas: search → detail → apply','Comparativo de variantes']},
      {n:'03',name:'Research',  chips:['Maze','Notion'],              desc:'User research synthesis mapped to catalog friction points and unmet needs.',
       contains:['Grilla de síntesis de research','Tarjetas de friction points','Tags de área de problema','Insights priorizados']},
      {n:'04',name:'Understand',chips:['Figma','FigJam'],             desc:'Persona map — who uses the catalog, what they need, and what blocks them.',
       contains:['Mapa de personas','Segmentos de usuario','Pares necesidad / bloqueo','Grilla por rol']},
      {n:'05',name:'Design',    chips:['Figma','Storybook'],          desc:'Redesigned catalog search and product detail flow — clarity-first information architecture.',
       contains:['UI de búsqueda rediseñada','Layout de product detail','Jerarquía de información','Comparativo antes / después']},
      {n:'06',name:'Hub',       chips:['Figma'],                      desc:'Central hub connecting all catalog interactions — a single control surface.',
       contains:['Hub central de interacciones','Mapa de conexiones entre secciones','Quick-links a acciones','Vista unificada']},
      {n:'07',name:'User flow', chips:['Pendo','Figma'],              desc:'Guided onboarding: Pendo tooltip → pre-checklist gate → step-by-step form with live cost.',
       contains:['Tooltip de Pendo (primer paso)','Gate con pre-checklist','Formulario paso a paso','Preview de costo en tiempo real']},
      {n:'08',name:'Publisher', chips:['Pendo','Figma'],              desc:'Publisher dashboard — add onboarding guides, define checklists, review submissions.',
       contains:['Dashboard de publisher','Constructor de guía de onboarding','Editor de checklist','Cola de submissions']},
      {n:'09',name:'Improved',  chips:['Figma'],                      desc:'Before vs after — same form, guided entry, inline context, cost before commit.',
       contains:['Estado "antes" (form original)','Estado "después" (form guiado)','Contexto inline en campos','Costo visible antes de confirmar']},
    ]
  },
  {
    id:'skills', name:'Skills', accent:'#d97757',
    src:'projects/skills-player.html',
    tryUrl:'try.html?p=projects/skills-player.html&beat=0',
    lede:'Taxonomy to a skill hub. Each beat is one product window.',
    beats:[
      {n:'01',name:'Mapping',   desc:'Skills taxonomy mapped across roles, seniority, and org units.',
       contains:['Grilla de taxonomía de skills','Eje de roles y seniority','Filtro por unidad org','Vista de árbol / mapa']},
      {n:'02',name:'Usage',     desc:'Which skills are actually used — frequency and recency data surfaced.',
       contains:['Gráfico de frecuencia de uso','Heatmap de recency','Ranking de top skills','Filtro por período']},
      {n:'03',name:'Segment',   desc:'Cohort segmentation — clusters of skill patterns by team and level.',
       contains:['Clusters de cohortes','Filtro por equipo y nivel','Tarjetas de patrón de skills','Vista comparativa']},
      {n:'04',name:'Research',  desc:'Research synthesis: where skills gap is felt most acutely by managers and ICs.',
       contains:['Síntesis de research','Vista managers vs ICs','Indicadores de severidad de gap','Insights mapeados por área']},
      {n:'05',name:'Understand',desc:'Mental models — how people think about skill growth and gap identification.',
       contains:['Diagramas de modelo mental','Flujos de crecimiento esperado','Cartas de identificación de gap','Comparativo de perspectivas']},
      {n:'06',name:'Design',    desc:'Redesigned skill profile and endorsement flow — mutual recognition built in.',
       contains:['Perfil de skill rediseñado','Flujo de endorsement','UI de reconocimiento mutuo','Estado de skill por área']},
      {n:'07',name:'Hub',       desc:'Skill hub: personal profile, team view, and org-wide leaderboard in one surface.',
       contains:['Perfil personal de skills','Vista de equipo','Leaderboard org-wide','Navegación entre vistas']},
      {n:'08',name:'Systems',   desc:'Systems view — skill health across the whole org, filterable by domain.',
       contains:['Vista sistémica de salud de skills','Filtro por dominio','Score de salud por área','Comparativo de dominios']},
    ]
  },
  {
    id:'dc', name:'DollarCity', accent:'#00a650',
    src:'projects/dollarcity-player.html',
    tryUrl:'try.html?p=projects/dollarcity-player.html&beat=3',
    lede:'Footage and product search on one desk. Try me is the review window, not the player film.',
    beats:[
      {n:'01',name:'Why',      desc:'Reviewers juggling tabs to watch footage and search products — everything moves to one screen.',
       contains:['Layout split: footage + búsqueda en paralelo','Panel de video izquierdo','Panel de producto derecho','Sin cambio de tab']},
      {n:'02',name:'Search',   desc:'Flagged transactions surface first — score, exceptions, and one-click path to footage.',
       contains:['Lista de transacciones flaggeadas','Badge de risk score','Excepciones visibles','Botón directo a footage']},
      {n:'03',name:'States',   desc:'Every request shows its state up front — queued, downloading, ready — no more wondering.',
       contains:['Indicadores de estado por request','Labels: queued / downloading / ready','Timeline de estado','Sin ambigüedad']},
      {n:'04',name:'Review',   desc:'Footage and receipt line up frame-by-frame — classify without leaving the video.',
       contains:['Video player + recibo sincronizados','Navegación frame-by-frame','Botones de clasificación inline','Sin salir del video']},
      {n:'05',name:'Expand',   desc:'One click expands footage full-frame — the receipt stays one tab away.',
       contains:['Vista expandida de footage','Recibo en tab adyacente','Control de minimizar','Transición suave']},
      {n:'06',name:'Requests', desc:'Every clip a reviewer pulled lives in one place — searchable, filterable, deletable in bulk.',
       contains:['Lista unificada de clips','Barra de búsqueda + filtros','Selección múltiple','Acción de borrado en bulk']},
      {n:'07',name:'New',      desc:'Requesting footage is one modal — camera, time range, and quality, nothing hidden.',
       contains:['Modal de nueva solicitud','Selector de cámara','Picker de rango de tiempo','Opción de calidad']},
      {n:'08',name:'Queue',    desc:'Downloads process in the background — reviewers keep working instead of watching a spinner.',
       contains:['Cola de descarga en background','Indicadores de progreso','Labels de estado','Revisores pueden seguir trabajando']},
      {n:'09',name:'Filters',  desc:'Filters and image-first product search replace memorized SKU lookups.',
       contains:['Panel de filtros','Búsqueda de producto por imagen','Cards de resultado con foto','Sin memorizacion de SKU']},
    ]
  },
  {
    id:'bc', name:'Blockchain 3D', accent:'#22d4c8',
    src:'projects/blockchain-player.html',
    tryUrl:'try.html?p=projects/blockchain-player.html&beat=1',
    lede:'Places on a 3D map. The window is the phone.',
    beats:[
      {n:'01',name:'Onboard',desc:'Welcome to your 3D map — content lives on places you own in space.',
       contains:['Phone mockup (393×852)','Drawer de bienvenida','Mapa 3D al fondo','Dots de pasos (3)','CTA "Continue"']},
      {n:'02',name:'Place',  desc:'Enter the map, long-press the street, confirm the address, style your pin.',
       contains:['Mapa 3D (Three.js city)','Gesto de long-press','Tarjeta de confirmación de dirección','Sheet de estilos de pin']},
      {n:'03',name:'Media',  desc:'Empty feed → choose source → device gallery → upload and publish.',
       contains:['Estado de feed vacío','Sheet de selección de fuente','Galería iOS (grid de fotos)','Confirmación de upload']},
      {n:'04',name:'Visitor',desc:'Find MY POI on the map — tap the pin, scroll reels, play full-screen.',
       contains:['Mapa con POI vivo','Pin tip card con thumbnail','Sheet de reels','Player full-screen']},
    ]
  },
  {
    id:'chek', name:'Chek', accent:'#7a3be0',
    src:'projects/chek-player.html',
    tryUrl:'try.html?p=projects/chek-player.html&beat=0',
    lede:'Credit card hub and flows. The window is the phone.',
    beats:[
      {n:'01',name:'Hub',     desc:'Credit card hub — balance, limit, quick actions, and recent moves at a glance.',
       contains:['UI de tarjeta de crédito','Balance + límite visibles','Botones de quick actions','Lista de movimientos recientes']},
      {n:'02',name:'Pay',     desc:'Pay card flow — amount input, date picker, confirmation, all in one modal.',
       contains:['Modal de pago','Input de monto','Date picker','Pantalla de confirmación']},
      {n:'03',name:'Limit',   desc:'Credit limit and balance breakdown — available, used, cash advance in one view.',
       contains:['Vista de desglose de límite','Barra: disponible / usado / cash advance','Detalle de límite','Comparativo visual']},
      {n:'04',name:'Moves',   desc:'Movements and statements — filterable transaction history with statement export.',
       contains:['Historial de transacciones','Filtro / búsqueda','Botón de exportar estado de cuenta','Agrupación por fecha']},
      {n:'05',name:'Security',desc:'Security help — card block and unblock, PIN change, fraud report flow.',
       contains:['Menú de seguridad','Toggle de bloqueo / desbloqueo','Flujo de cambio de PIN','Opción de reporte de fraude']},
      {n:'06',name:'Onboard', desc:'Onboarding — step-by-step first-time setup for a new credit card activation.',
       contains:['Pasos de onboarding','Formulario de activación','Indicador de progreso','Estado de completado']},
    ]
  },
  {
    id:'customs', name:'Customs ES', accent:'#e05c4a',
    src:'projects/customs-player.html',
    tryUrl:'try.html?p=projects/customs-player.html&beat=2',
    lede:'Office document to gate scan. Same contract as the other cases: window + once.',
    beats:[
      {n:'01',name:'Dashboard', desc:'Home shell — open documents, KPIs, filter and new-document action always visible.',
       contains:['Lista de documentos abiertos','Tiles de KPIs','Controles de filtro','Botón de nuevo documento']},
      {n:'02',name:'Select',    desc:'Pick the used-vehicle procedure — the legal path for the import opens.',
       contains:['Picker de tipo de procedimiento','Opción vehículo usado destacada','Acción de confirmación','Ruta legal visible']},
      {n:'03',name:'Form',      desc:'Fill operational facts: transport, office, importer, vehicle. Footer actions stay on screen.',
       contains:['Campo de transporte','Campo de oficina','Campo de importador','Campo de vehículo','Footer de acciones sticky']},
      {n:'04',name:'Review',    desc:'Review before the document exists — Generate stays in the window footer.',
       contains:['Resumen de todos los campos','Todos los datos legibles','Botón "Generar" en footer','Sin documento creado aún']},
      {n:'05',name:'Done',      desc:'Document created, same ID continues — ready for the field hand-off.',
       contains:['Confirmación de documento creado','ID del documento visible','Estado listo para campo','Hand-off a operativo']},
      {n:'06',name:'Present',   desc:'Driver presents, officer waits to scan — two devices, one operation.',
       contains:['Vista de dispositivo del conductor','Vista de dispositivo del oficial','Ambos en modo espera de scan','Una sola operación']},
      {n:'07',name:'Incident',  desc:'Scan fails — both screens say why. Driver and officer stay in the product.',
       contains:['Estado de error en ambas pantallas','Razón del error visible','Conductor y oficial en el producto','Sin salir del flujo']},
      {n:'08',name:'Release',   desc:'Second scan clears the vehicle — phone and tablet flip to approved.',
       contains:['Segundo scan exitoso','Ambas pantallas flip a "aprobado"','Vehículo liberado','Estado final claro']},
    ]
  }
];
