var EY_META=[
  {kind:'diagram',src:'projects/ey-01-measure.html',
   line:'Structure before diagnosis.<br><em>Map the product</em>.',
   cap:'Pages, flows, features, and events — tagged end to end.',
   under:'Sitemap + features + events — the instrumentation map.',
   chips:['Pendo','GA4','Paths'],
   contains:['Information architecture: Catalog home → Services / Request form / Workbench / Reports','Features tagged: Explore catalog, Service card, Required field, Submit request','Events: catalog_view · item_open · form_start · form_dropoff']},
  {scenes:[
    {kind:'window',src:'projects/ey-02-analyze.html?scene=home',name:'Home',
     line:'Users land on <em>platform home</em>.',
     cap:'Explore Catalog is the entry.',
     chips:['Pendo'],
     contains:['Nav Platform','Hero + CTA Explore Catalog']},
    {kind:'window',src:'projects/ey-02-analyze.html?scene=catalog',name:'Catalog',
     line:'Category cards — select <em>Services</em>.',
     cap:'Home → categories.',
     chips:['Pendo'],
     contains:['Sidebar Catalog','Cards: Services, Licenses, Kits']},
    {kind:'window',src:'projects/ey-02-analyze.html?scene=services',name:'Services',
     line:'Services — open <em>Workbench</em>.',
     cap:'List of offerings. Workbench is the target.',
     chips:['Pendo'],
     contains:['Service cards','Start on Workbench']},
    {kind:'window',src:'projects/ey-02-analyze.html?scene=form',name:'Form',
     line:'Form stalls on <em>required service</em>.',
     cap:'Name fills. Required field stays empty. Drop-off.',
     chips:['Pendo','Replay'],
     contains:['Workbench request form','Drop-off flag on required service']},
    {kind:'diagram',src:'projects/ey-02-analyze.html?scene=funnel',name:'Funnel',
     line:'Funnel makes the drop-off <em>obvious</em>.',
     cap:'Home 100% → Form 22%. Gráfico, no ventana.',
     chips:['Pendo'],
     contains:['Steps Home → Catalog → Services → Workbench → Form','Last step marked drop-off']}
  ]},
  {kind:'diagram',src:'projects/ey-naked.html?beat=2&kind=diagram',
   line:'Analytics show <em>where</em>.<br>Research explains <em>why</em>.',
   cap:'Interviews · scores · replay session · task path.',
   under:'Evidence stack — quotes, session, path.',
   chips:['Maze','Pendo','Optimal'],
   contains:['Interviews (quotes)','CSAT · NPS · CES','Replay de sesión en el form','Task path Maze · 34% success']},
  {kind:'diagram',src:'projects/ey-naked.html?beat=3&kind=diagram',
   line:'Not opinions.<br><em>Evidence becomes tasks.</em>',
   cap:'Findings left · owners right.',
   under:'Findings owned by design, product, content, analytics.',
   chips:['FigJam','Pendo'],
   contains:['Findings: no checklist, labels unclear, no onboarding','Owners: Design, Product, Content, Analytics']},
  {kind:'window',src:'projects/ey-naked.html?beat=4&kind=window',
   line:'Design — <em>by hand</em><br>and <em>with AI</em>. In parallel.',
   cap:'Split canvas → merge into one proposal.',
   under:'Proposal: checklist before the form.',
   chips:['Figma','Replit','Factory'],
   contains:['Canvas Figma (frames a mano)','Prompt AI (Factory / Replit)','Merge → proposal con checklist']},
  {kind:'window',src:'projects/ey-naked.html?beat=5&kind=window',
   line:'One <em>analytics hub</em>.<br>The full cycle stays visible.',
   cap:'Hub first — then open Signals.',
   under:'Land on the hub — then open Signals.',
   chips:['Pendo','Replit','Factory'],
   contains:['Hub: Recovery rate, time on form, guide views','Signals: drop-off required service, CES, paths']},
  {kind:'window',src:'projects/ey-naked.html?beat=6&kind=window',
   line:'From intent to request —<br><em>guided, gated, clear</em>.',
   cap:'Onboarding tooltip → pre-checklist → step-by-step form with live cost.',
   under:'Pendo tooltip → gate → form with live cost.',
   chips:['Pendo','Fabric'],
   contains:['Tooltip Pendo en home','Pre-checklist gate','Form paso a paso + cost badge']},
  {kind:'window',src:'projects/ey-naked.html?beat=7&kind=window',
   line:'Publisher view —<br><em>configure</em> from the inside.',
   cap:'Add onboarding guides, define checklists, review submissions.',
   under:'Publisher dashboard — checklist builder + Pendo guides.',
   chips:['Pendo','Fabric'],
   contains:['Checklist builder (Workbench)','Pendo guides activas','Nav: Listings / Guides / Checklists / Submissions']},
  {kind:'window',src:'projects/ey-naked.html?beat=8&kind=window',
   line:'<em>What changed</em> — friction to guided flow.',
   cap:'Same form. Different experience. Visual proof.',
   under:'Before vs after — same Workbench request, guided entry.',
   chips:['Fabric','Pendo'],
   contains:['Columna Before: form frío','Columna After: form guiado','Misma superficie, distinta experiencia']}
];
