var EY_META=[
  {kind:'diagram',src:'projects/ey-01-measure.html',
   line:'Structure before diagnosis.<br><em>Map the product</em>.',
   cap:'Sitemap + events. Diagrama, no browser.',
   chips:['Pendo','GA4'],
   contains:['IA tree','Features tagged','Events catalog_view → form_dropoff']},
  {scenes:[
    {kind:'window',src:'projects/ey-02-analyze.html?scene=path',name:'Path',
     line:'Home → catalog → Services → <em>form</em>.',
     cap:'Una secuencia. Browser + DS del catálogo.',
     chips:['Pendo'],
     contains:['Hero + Explore Catalog','Tiles de marketplace','Workbench + order $0']},
    {kind:'diagram',src:'projects/ey-funnel.html',name:'Funnel',
     line:'El path visto como <em>funnel</em>.',
     cap:'Gráfico. Sin browser.',
     chips:['Pendo'],
     contains:['Home → Required','Último paso en rojo']}
  ]},
  {kind:'diagram',src:'projects/ey-research.html',
   line:'Analytics show <em>where</em>. Research explains <em>why</em>.',
   cap:'Quotes + replay + task. Sin browser.',
   chips:['Maze','Pendo'],
   contains:['Interviews','Scores','Replay','Task study']},
  {kind:'diagram',src:'projects/ey-understand.html',
   line:'Not opinions. <em>Evidence becomes tasks.</em>',
   cap:'Finding → owner. Sin browser.',
   chips:['FigJam'],
   contains:['No checklist → Design','Unlabeled required → Content','No onboarding → Analytics']},
  {kind:'window',src:'projects/ey-design.html',
   line:'I can design <em>by hand</em> and with <em>every agent</em>.',
   cap:'Figma · Claude Code · Cursor · Factory · Replit. Then a screen: Design ready.',
   chips:['Figma','Claude','Cursor','Factory','Replit'],
   contains:['Figma workshop','Agent + CLI workshop','Publisher screen ready']},
  {kind:'window',src:'projects/ey-hub.html',
   line:'The Hub is a <em>product I built</em>.',
   cap:'Alarms → Workbench → funnels + features.',
   chips:['Factory','Replit','Figma','Pendo'],
   contains:['Alarms','Workbench filter','Funnels + feature list']},
  {scenes:[
    {kind:'window',src:'projects/ey-req.html?scene=enter',name:'Enter',
     line:'Marketplace — requirements <em>on the card</em>.',
     cap:'Chip + lines on the tile. Callout on what is new.',
     chips:['Catalog'],
     contains:['Dense catalog','Requirements on card','Callout + ring']},
    {kind:'window',src:'projects/ey-req.html?scene=pedir',name:'Pedir',
     line:'Customize → <em>Configure is the win</em>.',
     cap:'Chat + onboarding stay. Success fires as they enter step 2.',
     chips:['Chat','Form'],
     contains:['Customize fields','Success at Configure','Chat replies']}
  ]},
  {scenes:[
    {kind:'window',src:'projects/ey-pub.html?scene=workspace',name:'Workspace',
     line:'Publisher home — <em>queue is the work</em>.',
     cap:'Then Publish new item → pick Service.',
     chips:['Queue'],
     contains:['Dense workspace','Pending / corrections','Type = Service']},
    {kind:'window',src:'projects/ey-pub.html?scene=armar',name:'Armar',
     line:'File or hand → guidance → onboard → <em>AI then human</em>.',
     cap:'Tooltips from a prior list or typed. Review is last.',
     chips:['Studio','AI'],
     contains:['Load file / add fields','Guidance pick','Onboard builder','AI pass + human']}
  ]}
];
